#!/usr/bin/env sh

packages_count=''
display='${hostname}\n\n${kernel}\n${uptime}\n${packages_count}\n${shell}\n${dist_name}\n${dist_birth}\n\n${DARK_COLORS}\n${LIGHT_COLORS}'
experimental='false'

_HELP() {
	printf '%s\n' "
  USAGE: sfetch [opts...] [args...]

  OPTIONS:
    -h  Show this help message.
    -e  Enables experimental code in emerge package manager.
    -d  Displays only the described infos.
    -t  Displays the -d default template.

  VERSION:
    sfetch v0.1
  "

	exit 0
}

GET_PACKAGES_COUNT() {
	if [ -f /usr/bin/pacman ]; then
		packages_count="󰣇 $(pacman -Q | wc -l)"
	elif [ -f /usr/bin/apt-cache ]; then
		packages_count=" $(apt-cache stats | head -n 1 | sed ' s/Total package names: //' | sed 's/ .*//')"
	elif [ -f /usr/bin/dnf ]; then
		packages_count=" $(rpm -qa | wc -l)"
	elif [ -f /usr/bin/portage ] && [ $experimental = 'true' ]; then
		packages_count=" $(emerge -evp --deep world)"
	fi

	if [ -f /usr/bin/flatpak ]; then
		packages_count="$packages_count  $(flatpak list | wc -l)"
	fi

	if [ -f /usr/bin/snap ]; then
		packages_count="$packages_count  $(snap list | wc -l)"
	fi
}

DISPLAY_FETCH() {
	. /etc/os-release

	hostname="  ${USER}@$(cat /proc/sys/kernel/hostname)"
	kernel=" 󰌽 Kernel: $(uname -r)"
	uptime=" 󰥔 Uptime: $(uptime -p | sed 's/up\s//')"
	shell="  Shell: $(${SHELL} --version | sed 's/(.*$//')"
	dist_name="  Distro: ${NAME} ${VERSION}"
	dist_birth="  Created in: $(stat -c %w / | sed 's/\..*$//')"
	GET_PACKAGES_COUNT # call function to get packages
	packages_count="  Packages: ${packages_count}"

	# Colors
	DARK_COLORS="\e[1;30m ██\e[1;31m ██\e[1;32m ██\e[1;33m ██\e[1;34m ██\e[1;35m ██\e[1;36m ██\e[1;37m ██"
	LIGHT_COLORS="\e[1;90m ██\e[1;91m ██\e[1;92m ██\e[1;93m ██\e[1;94m ██\e[1;95m ██\e[1;96m ██\e[1;97m ██"

	display="$(eval "printf \"${display}\"")"
	printf "%b\n" "\n${display}\n"

	exit 0
}

while getopts ':hetd:' option; do
	case "$option" in
	e) experimental="true" ;;
	h) _HELP ;;
	d) display="$OPTARG" ;;
	t)
		printf '%s\n' "'$display'"
		exit 0
		;;
	:)
		printf "%s\n" "Option -${OPTARG} requires an argument."
		exit 1
		;;
	\?)
		printf "%s\n" "Invalid option: -${OPTARG}."
		exit 1
		;;
	esac
done

shift $(("${OPTIND}" - 1))

[ -z "$1" ] && { DISPLAY_FETCH; }
