#!/usr/bin/env sh

packages_count=''
experimental='false'

_HELP() {
	printf "
  USAGE: sfetch [opts...] [args...]

  OPTIONS:
    -h  Show this help message.
    -e  Enables experimental code in emerge package manager.

  VERSION:
    sfetch v0.1
  "
}

GET_PACKAGES_COUNT() {
	if [ -f /usr/bin/pacman ]; then
		packages_count="󰣇 $(pacman -Q | wc -l)"
	elif [ -f /usr/bin/apt-cache ]; then
		packages_count=" $(apt-cache stats | head -n 1 | sed ' s/Total package names: //' | sed 's/ .*//')"
	elif [ -f /usr/bin/dnf ]; then
		packages_count=" $(rpm -qa | wc -l)"
	elif [ -f /usr/bin/portage ] && [ $experimental = 'true' ]; then
		packages_count=" $(emerge -evp --deep world)"
	fi

	if [ -f /usr/bin/flatpak ]; then
		packages_count="$packages_count  $(flatpak list | wc -l)"
	fi

	if [ -f /usr/bin/snap ]; then
		packages_count="$packages_count  $(snap list | wc -l)"
	fi
}

DISPLAY_FETCH() {
	. /etc/os-release

	hostname="\n  ${USER}@$(cat /proc/sys/kernel/hostname)\n"
	kernel="\n 󰌽 Kernel: $(uname -r)"
	uptime="\n 󰥔 Uptime: $(uptime -p | sed 's/up\s//')"
	shell="\n  Shell: $(${SHELL} --version | sed 's/(.*$//')"
	dist_name="\n  Distro: ${NAME} ${VERSION}"
	dist_birth="\n  Created in: $(stat -c %w / | sed 's/\..*$//')"
	GET_PACKAGES_COUNT # call function to get packages
	packages_count="\n  Packages: ${packages_count}"

	# Colors
	DARK_COLORS="\n\e[1;30m ██\e[1;31m ██\e[1;32m ██\e[1;33m ██\e[1;34m ██\e[1;35m ██\e[1;36m ██\e[1;37m ██"
	LIGHT_COLORS="\n\e[1;90m ██\e[1;91m ██\e[1;92m ██\e[1;93m ██\e[1;94m ██\e[1;95m ██\e[1;96m ██\e[1;97m ██\n"

	printf "%b\n" "${hostname}${kernel}${uptime}${packages_count}${shell}${dist_name}${dist_birth}\n${DARK_COLORS}${LIGHT_COLORS}"
}

while getopts ':he' option; do
	case "$option" in
	e) experimental="true" ;;
	h) _HELP ;;
	:)
		printf "%s" "Option -${OPTARG} requires an argument."
		exit 1
		;;
	\?)
		printf "%s" "Invalid option: -${OPTARG}."
		exit 1
		;;
	esac
done

[ -z "$1" ] && { DISPLAY_FETCH; }
